# **Importing Important Libraries**

---



In [ ]:
import numpy as np
import pandas as pd

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
df = pd.DataFrame() #making the DataFrame
df = pd.read_csv('/content/spam.csv',encoding='iso-8859-1') #Extracting the Dataset from csv file
df.head(20) #checking first 20 datasets

v1  ... Unnamed: 4
0    ham  ...        NaN
1    ham  ...        NaN
2   spam  ...        NaN
3    ham  ...        NaN
4    ham  ...        NaN
5   spam  ...        NaN
6    ham  ...        NaN
7    ham  ...        NaN
8   spam  ...        NaN
9   spam  ...        NaN
10   ham  ...        NaN
11  spam  ...        NaN
12  spam  ...        NaN
13   ham  ...        NaN
14   ham  ...        NaN
15  spam  ...        NaN
16   ham  ...        NaN
17   ham  ...        NaN
18   ham  ...        NaN
19  spam  ...        NaN

[20 rows x 5 columns]

In [ ]:
df.tail(20) #checking last 20 datasets

v1  ... Unnamed: 4
5552   ham  ...        NaN
5553   ham  ...        NaN
5554   ham  ...        NaN
5555   ham  ...        NaN
5556   ham  ...        NaN
5557   ham  ...        NaN
5558   ham  ...        NaN
5559   ham  ...        NaN
5560   ham  ...        NaN
5561   ham  ...        NaN
5562   ham  ...        NaN
5563   ham  ...        NaN
5564   ham  ...        NaN
5565   ham  ...        NaN
5566  spam  ...        NaN
5567  spam  ...        NaN
5568   ham  ...        NaN
5569   ham  ...        NaN
5570   ham  ...        NaN
5571   ham  ...        NaN

[20 rows x 5 columns]

In [ ]:
df.shape #checking the shape

(5572, 5)

▶ We can see there are **5572** data points

In [ ]:
df.info() #checking the information of the data set

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


▶ As per information there are **5 object** type data in the dataset

---





▶ We don't need **Unnamed 2**, **Unnamed 3**, **Unnamed 4** column

---


because those columns are full of **NaN values**. So we will **drop** 

---

all those columns.

In [ ]:
df=df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   v1      5572 non-null   object
 1   v2      5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


▶ We still have **2 object** type data that we have to change

In [ ]:
df['v1'].value_counts() #checking the value counts of column 'v1'

ham     4825
spam     747
Name: v1, dtype: int64

In [ ]:
mail={'ham':0,'spam':1}
df['v1'] = df['v1'].map(mail)
df

v1                                                 v2
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...
...   ..                                                ...
5567   1  This is the 2nd time we have tried 2 contact u...
5568   0              Will Ì_ b going to esplanade fr home?
5569   0  Pity, * was in mood for that. So...any other s...
5570   0  The guy did some bitching but I acted like i'd...
5571   0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   v1      5572 non-null   int64 
 1   v2      5572 non-null   object
dtypes: int64(1), object(1)
memory usage: 87.2+ KB


▶ Now all we have to deal with the **text part** of column '**v2**'

In [ ]:
df['v2']=df['v2'].str.lower() #converting the text of column 'v2' into lower case letter


Importing Some more Important libraries like **re**, **string**, **nltk**, **Stopwords**

In [ ]:
import re
import string
import nltk
nltk.download('stopwords') #it will download all the stopwords
from nltk.corpus import stopwords
swords=stopwords.words('english') #saving all the stopwords as swords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
swords #let's check the stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
def remove_stopwords(v2):
    return " ".join([word for word in str(v2).split() if word not in swords]) #making the function that will remove all the stopwords from column 'v2'

df['v2'] = df['v2'].apply(lambda v2: remove_stopwords(v2)) #calling the function here
df['v2'].head(20)

0     go jurong point, crazy.. available bugis n gre...
1                         ok lar... joking wif u oni...
2     free entry 2 wkly comp win fa cup final tkts 2...
3             u dun say early hor... u c already say...
4               nah think goes usf, lives around though
5     freemsg hey darling 3 week's word back! i'd li...
6     even brother like speak me. treat like aids pa...
7     per request 'melle melle (oru minnaminunginte ...
8     winner!! valued network customer selected rece...
9     mobile 11 months more? u r entitled update lat...
10    i'm gonna home soon want talk stuff anymore to...
11    six chances win cash! 100 20,000 pounds txt> c...
12    urgent! 1 week free membership å£100,000 prize...
13    i've searching right words thank breather. pro...
14                                   date sunday will!!
15    xxxmobilemovieclub: use credit, click wap link...
16                           oh k...i'm watching here:)
17    eh u remember 2 spell name... yes did. v n

Now we can see there are lots of punctuations in the text part that we 

---

have to remove

In [ ]:
def remove_punctuations(v2):  #making a function that will remove the punctuations
    translator = str.maketrans('', '', string.punctuation) 
    return v2.translate(translator)

df['v2']= df['v2'].apply(lambda x: remove_punctuations(x)) #calling the function
df['v2'].head(20)

0     go jurong point crazy available bugis n great ...
1                               ok lar joking wif u oni
2     free entry 2 wkly comp win fa cup final tkts 2...
3                   u dun say early hor u c already say
4                nah think goes usf lives around though
5     freemsg hey darling 3 weeks word back id like ...
6     even brother like speak me treat like aids patent
7     per request melle melle oru minnaminunginte nu...
8     winner valued network customer selected receiv...
9     mobile 11 months more u r entitled update late...
10    im gonna home soon want talk stuff anymore ton...
11    six chances win cash 100 20000 pounds txt csh1...
12    urgent 1 week free membership å£100000 prize j...
13    ive searching right words thank breather promi...
14                                     date sunday will
15    xxxmobilemovieclub use credit click wap link n...
16                                 oh kim watching here
17    eh u remember 2 spell name yes did v naugh

As it is **Spam mail** Dataset. So there is possibility of the presence of different **url** of **websites**. So we have to remove all those urls for the sake of trainning 

In [ ]:
def remove_URLs(data):  #making the function that will remove all the URL
    return re.sub('((www.[^s]+)|(https?://[^s]+))',' ',data)

df['v2'] = df['v2'].apply(lambda x: remove_URLs(x)) #calling the function
df['v2'].tail(20)

5552    safe trip nigeria wish happiness soon company ...
5553                                 hahahause brain dear
5554    well keep mind ive got enough gas one round tr...
5555    yeh indians nice tho kane bit he shud go 4 dri...
5556            yes have thats u texted pshewmissing much
5557    no meant calculation same ltgt units ltgt  sch...
5558                                 sorry ill call later
5559                       next ltgt hours imma flip shit
5560                              anything lor juz us lor
5561          get dump heap mom decided come lowes boring
5562    ok lor sony ericsson salesman ask shuhui say q...
5563                                   ard 6 like dat lor
5564                    wait til least wednesday see get 
5565                                              huh lei
5566    reminder o2 get 250 pounds free call credit de...
5567    2nd time tried 2 contact u u å£750 pound prize...
5568                          ì b going esplanade fr home
5569          

In [ ]:
def remove_numbers(data):
    return re.sub('[0-9]+', '', data)
    
df['v2'] = df['v2'].apply(lambda x: remove_numbers(x))
df['v2'].head(20)

0     go jurong point crazy available bugis n great ...
1                               ok lar joking wif u oni
2     free entry  wkly comp win fa cup final tkts st...
3                   u dun say early hor u c already say
4                nah think goes usf lives around though
5     freemsg hey darling  weeks word back id like f...
6     even brother like speak me treat like aids patent
7     per request melle melle oru minnaminunginte nu...
8     winner valued network customer selected receiv...
9     mobile  months more u r entitled update latest...
10    im gonna home soon want talk stuff anymore ton...
11    six chances win cash   pounds txt csh send  co...
12    urgent  week free membership å£ prize jackpot ...
13    ive searching right words thank breather promi...
14                                     date sunday will
15    xxxmobilemovieclub use credit click wap link n...
16                                 oh kim watching here
17    eh u remember  spell name yes did v naught

In [ ]:
review_lines = list()
lines = df['v2'].values.tolist()
words = [word for word in lines if word.isalpha()]


In [ ]:
mail = df['v2'].tolist()
subs = df['v1'].tolist()

In [ ]:
print(mail[57])
print(subs[57])

sorry ill call later meeting
0


In [ ]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(mail)
word_index = tokenizer.word_index

size_of_vocab=len(word_index) + 1 
print("Vocab Size = %d"%size_of_vocab)

Vocab Size = 8549


In [ ]:
indices = np.arange(len(mail))
print(indices)
np.random.shuffle(indices)
print(indices)

[   0    1    2 ... 5569 5570 5571]
[2577 1126 1482 ... 2752 2282  899]


In [ ]:
mail=np.array(mail)[indices.astype(int)]
subs=np.array(subs)[indices.astype(int)]

In [ ]:
train_size = int(len(mail) * 0.9)

train_mail = mail[0: train_size]
test_mail = mail[train_size:]
train_subs = subs[0: train_size]
test_subs = subs[train_size:]

training_subs_final = np.array(train_subs)
testing_subs_final = np.array(test_subs)

In [ ]:
print("Shape of training dataset X : "+str(len(train_mail)))
print("Shape of training dataset Y : "+str(len(training_subs_final)))
print("Shape of testing dataset X : "+str(len(test_mail)))
print("Shape of testing dataset Y : "+str(len(testing_subs_final)))

Shape of training dataset X : 5014
Shape of training dataset Y : 5014
Shape of testing dataset X : 558
Shape of testing dataset Y : 558


In [ ]:
embedding_dim = 100
max_length = 100
trunc_type='post'
padding_type='post'

In [ ]:
training_sequences = tokenizer.texts_to_sequences(train_mail)
training_padded = pad_sequences(training_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)

testing_sequences = tokenizer.texts_to_sequences(test_mail)
testing_padded = pad_sequences(testing_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)

In [ ]:
print(train_mail[20])
print(train_subs[20])
training_padded[20]


watching cartoon listening music amp eve go temple amp church u
0


array([ 253, 1562, 1563,  430,   90,  519,    6, 1826,   90, 1827,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0], dtype=int32)

In [ ]:
embeddings_index = dict()
f = open('/content/drive/MyDrive/glove.twitter.27B.100d.txt')

for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs

f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

Loaded 1193514 word vectors.


In [ ]:
embedding_matrix = np.zeros((size_of_vocab, 100))

for word, i in tokenizer.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

In [ ]:
from keras.models import *
from keras.layers import *
from keras.callbacks import *

embedding_layer = Embedding(size_of_vocab, embedding_dim, weights = [embedding_matrix], input_length = max_length, trainable = False)
model = Sequential()
model.add(embedding_layer)

model.add(LSTM(200, dropout = 0.2))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation = "sigmoid"))

model.compile(optimizer='adam', loss='binary_crossentropy',metrics=["acc"])

es = EarlyStopping(monitor='val_loss', mode='min', verbose=1,patience=3)  
mc=ModelCheckpoint('best_model.h5', monitor='val_acc', mode='max', save_best_only=True,verbose=1)
reduce_lr = ReduceLROnPlateau(monitor = 'val_acc', factor = 0.1,min_lr = 0.01,verbose=1)


print(model.summary())


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 100, 100)          854900    
                                                                 
 lstm_1 (LSTM)               (None, 200)               240800    
                                                                 
 dense_2 (Dense)             (None, 64)                12864     
                                                                 
 dense_3 (Dense)             (None, 1)                 65        
                                                                 
Total params: 1,108,629
Trainable params: 253,729
Non-trainable params: 854,900
_________________________________________________________________
None


In [ ]:
history = model.fit(training_padded,training_subs_final,batch_size=1024,epochs=15,validation_data=(testing_padded,testing_subs_final),verbose=1,callbacks=[es,mc,reduce_lr])

Epoch 1/15
5/5 [==============================] - ETA: 0s - loss: 0.6746 - acc: 0.8644
Epoch 00001: val_acc improved from -inf to 0.85842, saving model to best_model.h5
5/5 [==============================] - 7s 339ms/step - loss: 0.6746 - acc: 0.8644 - val_loss: 0.6120 - val_acc: 0.8584 - lr: 0.0010
Epoch 2/15
5/5 [==============================] - ETA: 0s - loss: 0.5334 - acc: 0.8668
Epoch 00002: val_acc did not improve from 0.85842
5/5 [==============================] - 1s 165ms/step - loss: 0.5334 - acc: 0.8668 - val_loss: 0.4060 - val_acc: 0.8584 - lr: 0.0010
Epoch 3/15
5/5 [==============================] - ETA: 0s - loss: 0.4544 - acc: 0.8668
Epoch 00003: val_acc did not improve from 0.85842
5/5 [==============================] - 1s 162ms/step - loss: 0.4544 - acc: 0.8668 - val_loss: 0.4355 - val_acc: 0.8584 - lr: 0.0010
Epoch 4/15
5/5 [==============================] - ETA: 0s - loss: 0.3133 - acc: 0.8773
Epoch 00004: val_acc improved from 0.85842 to 0.95161, saving model to bes

In [ ]:
with open('model_architecture_Spam_classifier.json','w') as f:
    f.write(model.to_json())

In [ ]:
model.save_weights('Spam_Classifier.h5')

In [ ]:
test_sample_1 = "How are you? need to talk"
test_sample_2 = "You won’t believe this,A doctor in Arizona has discovered the root-cause of high blood sugar.It has nothing to do with eating carbs or sugar….But with “Beta Cells” inside the pancreas…Watch his video while it’s still up…Stay safe,Your Name"

test_samples = [test_sample_1, test_sample_2]

test_samples=[i.lower() for i in test_samples]
test_samples=[remove_stopwords(i) for i in test_samples]
test_samples=[remove_punctuations(i) for i in test_samples]
test_samples=[remove_URLs(i) for i in test_samples]
test_samples=[remove_numbers(i) for i in test_samples]

In [ ]:
test_samples

['you need talk',
 'won’t believe thisa doctor arizona discovered rootcause high blood sugarit nothing eating carbs sugar…but “beta cells” inside pancreas…watch video it’s still up…stay safeyour name']

In [ ]:
test_samples_tokens = tokenizer.texts_to_sequences(test_samples)
test_samples_tokens_pad = pad_sequences(test_samples_tokens, maxlen=max_length)

#predict
model.predict(x=test_samples_tokens_pad)

array([[0.02864225],
       [0.02889125]], dtype=float32)